library(quanteda); library(tictoc)
tic("Total")
dfm_paths <- list.files("Assets/RDS/dfm", full.names = TRUE)
dfm_paths
saveDir <- "Assets/RDS/df"
    tic("Unigram Dataframe")
unigrams_dfm <- readRDS(dfm_paths[3])
unigrams_df <- convert(unigrams_dfm, to = "data.frame")
saveRDS(unigrams_df, paste(saveDir, "unigrams_df.rds", sep = "/"))
rm(unigrams_dfm, unigrams_df)
    toc()
    tic("Bigram Dataframe")
bigrams_dfm <- readRDS(dfm_paths[1])
bigrams_df <- convert(bigrams_dfm, to = "data.frame")
saveRDS(bigrams_df, paste(saveDir, "bigrams_df.rds", sep = "/"))
rm(bigrams_dfm, bigrams_df)
    toc()
    tic("Trigram Dataframe")
trigrams_dfm <- readRDS(dfm_paths[2])
trigrams_df <- convert(trigrams_dfm, to = "data.frame")
rm(trigrams_dfm)
saveRDS(trigrams_df, paste(saveDir, "trigrams_df.rds", sep = "/"))
rm(trigrams_df)
    toc()